spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/peerforge
    username: Dushyant
    password: Saurabh@7

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  port: 8080